string ::= "a-z|A-Z"*
number ::= 0-9*
literal ::=  number | string | "true" | "false" | "nil" ;
expression ::=  literal | unary | binary | grouping ;
grouping ::=  "(" expression ")" ;
unary ::= ( "-" | "!" ) expression ;
binary ::=  expression operator expression ;
operator ::= "==" | "!=" | "<" | "<=" | ">" | ">=" | "+" | "-" | "*" | "/" ;